### ISSUE TITLE
Not able to move binary

### ISSUE THREAD

**Issue by nfcampos** [zeit/now-desktop#282]
Error: Command failed: mv /var/folders/fx/70r4sn6960qd8jj24y2761h80000gn/T/tmp-1171V7WSv99B3a4I/now-macos /usr/local/bin/now

**Comment by leo** [comment]
Should be fixed with the next update!

**Comment by Dids** [comment]
@leo Did you guys also fix this for Windows, because I'm definitely still getting this?

**Comment by leo** [comment]
@Dids What's your error message? Should be different for windows. Are you on the latest version?

**Comment by Dids** [comment]
@leo After hitting the button to install the CLI, I get a UAC prompt, and after that it throws an error dialog that says "Not able to move binary". Latest version of now-desktop, just downloaded and installed it.

**Comment by nvsio** [comment]
![image](https://www.dropbox.com/s/qt7np6grpxaepmk/Screenshot%202017-05-20%2022.07.03.png?dl=1)

**Comment by rauchg** [comment]
@nvsio you can also run `npm install -g now` temporarily until we figure out your specific issue

**Comment by leo** [comment]
An update is coming very soon. If it doesn't fix the issue, please let us know!
